// Email справочник пользователей Б24 (username = email в формате name.l@prolabsupport.kz)
const USER_EMAILS = {
  4: 'kuanysh.e@prolabsupport.kz',
  7: 'miras.a@prolabsupport.kz',
  8: 'rustam.a@prolabsupport.kz',
  9: 'murat.b@prolabsupport.kz',
  10: 'assylbek.o@prolabsupport.kz',
  11: 'gauhar.a@prolabsupport.kz',
  12: 'aizhan.b@prolabsupport.kz',
  13: 'nazerke.m@prolabsupport.kz',
  14: 'kanat.zh@prolabsupport.kz',
  15: 'semen.zh@prolabsupport.kz',
  16: 'dameli.s@prolabsupport.kz',
  18: 'alexandr.y@prolabsupport.kz',
  19: 'yerlan.a@prolabsupport.kz',
  20: 'ainur.r@prolabsupport.kz',
  21: 'zhadyra.s@prolabsupport.kz',
  22: 'daniyar.o@prolabsupport.kz',
  23: 'bakhytgul.d@prolabsupport.kz',
  24: 'shokan.r@prolabsupport.kz',
  25: 'rauan.zh@prolabsupport.kz',
  26: 'azamat.a@prolabsupport.kz',
  27: 'marzhan.d@prolabsupport.kz',
  28: 'project@prolabsupport.kz',
  29: 'boris.e@prolabsupport.kz',
  31: 'techsupport@prolabsupport.kz',
  32: 'akerke.sh@prolabsupport.kz',
  33: 'annel.l@prolabsupport.kz',
  34: 'gulnur.k@prolabsupport.kz',
  36: 'aruna.b@prolabsupport.kz',
  37: 'akgulim.s@prolabsupport.kz',
  38: 'talant.a@prolabsupport.kz',
  39: 'mansur.s@prolabsupport.kz',
  40: 'kakha.ch@prolabsupport.kz',
  41: 'accountant@prolabsupport.kz',
  44: 'bakytzhan.sh@prolabsupport.kz',
  45: 'azat.m@prolabsupport.kz',
  46: 'zhandos.k@prolabsupport.kz',
  47: 'dmitry.s@prolabsupport.kz',
  48: 'daryn.n@prolabsupport.kz',
  50: 'nurbek.i@prolabsupport.kz',
  55: 'nurkhat.o@prolabsupport.kz',
  67: 'ainel.s@prolabsupport.kz',
  68: 'igor.b@prolabsupport.kz',
  71: 'azamat.ali@prolabsupport.kz',
  73: 'yerassyl.m@prolabsupport.kz',
  76: 'askhat.k@prolabsupport.kz',
  77: 'adil.t@prolabsupport.kz',
  78: 'dmitriy.v@prolabsupport.kz',
  79: 'arman.man@prolabsupport.kz',
  85: 'maxim.m@prolabsupport.kz',
  86: 'amanzhol.s@prolabsupport.kz',
  88: 'assem.zh@prolabsupport.kz',
  90: 'yerkanat.s@prolabsupport.kz',
};

module.exports = { USER_EMAILS };
